apiVersion: v1
kind: Service
metadata:
  name: {{ include "task1.fullname" . }}
  labels:
    {{- include "task1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.logs.port }}
      targetPort: logs
      protocol: TCP
      name: logs
    - port: {{ .Values.service.soap.port }}
      targetPort: soap
      protocol: TCP
      name: soap
  selector:
    {{- include "task1.selectorLabels" . | nindent 4 }}
